### ISSUE TITLE
Menu help button

### ISSUE THREAD

**Issue by dobrodejm** [Group-9-Semester-4/ninja-game#106]
Create a help menu explaining the flow of the game. When user clicks on the help button a slideshow of different screens with text is displayed. or something like that

**Comment by samlama111** [comment]
Main menu – Ninjaspillet can be played alone or with friends. ‘Start’ for you to play at your own pace without anyone interfering, ‘multiplayer’ to compete with your friends. 

Choose card set – To earn points and defeat the evil ninja, you have to pick the cards you want to play with. You can choose from one of the predefined card sets & you can pick or discard individual cards.  

Choose game mode – Choose a way in which you want to compete against others. Basic game mode is made of turns. In each turn, players try to complete the card as fast as possible, once they finish, they wait for the next turn. 

Concurrent game mode is like a sprint, each player tries to complete as many cards as possible. The fastest player wins. 

Game screen – Draw cards to get exercise. Some exercise you can do at your own pace, some are time limited. Don’t worry, if you don’t like your card, you can always redraw! 
If you feel ready and you have acquired enough points, you can face the final boss. 

Boss fight – Hit the evil ninja with your shurikens! The more cards you complete, the more ammo you get to throw at your enemy. Earn points depending on how accurate you are then see how well your friends did.
