### ISSUE TITLE
Add help text into Scenes

### ISSUE THREAD

**Issue by dobrodejm** [Group-9-Semester-4/ninja-game#140]
All scenes, where the user needs to make a choice should have a help text (ideally hidden behind a lightbulb icon or "help" button). 
Go through the entire singleplayer game from start to boss fight and note down where the help text could be useful to the user (if you think it's simple enough for a child to understand, help text probably isn't necessary )

**Comment by samlama111** [comment]
Main menu – Ninjaspillet can be played alone or with friends. ‘Start’ for you to play at your own pace without anyone interfering, ‘multiplayer’ to compete with your friends. 

Choose card set – To earn points and defeat the evil ninja, you have to pick the cards you want to play with. You can choose from one of the predefined card sets & you can pick or discard individual cards.  

Choose game mode – Choose a way in which you want to compete against others. Basic game mode is made of turns. In each turn, players try to complete the card as fast as possible, once they finish, they wait for the next turn. 

Concurrent game mode is like a sprint, each player tries to complete as many cards as possible. The fastest player wins. 

Game screen – Draw cards to get exercise. Some exercise you can do at your own pace, some are time limited. Don’t worry, if you don’t like your card, you can always redraw! 
If you feel ready and you have acquired enough points, you can face the final boss. 

Boss fight – Hit the evil ninja with your shurikens! The more cards you complete, the more ammo you get to throw at your enemy. Earn points depending on how accurate you are then see how well your friends did.
